/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/journeys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create journey and compute alternatives */
    post: operations['createJourney']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/journeys/{id}': {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    /**
     * Full journey — summary + legs combined (initial screen load only)
     * @description Called once on AlternativesScreen initial load.
     *     Do NOT use for polling — use GET /summary instead.
     */
    get: operations['getJourney']
    put?: never
    post?: never
    /**
     * Terminate monitoring and cancel poller goroutine
     * @description 204 on success. 404 on unknown or expired journey ID.
     *     Second DELETE on same ID returns 404 — not silently idempotent.
     */
    delete: operations['deleteJourney']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/journeys/{id}/summary': {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    /** Compact status — fast polling path (30s foreground / 90s background tab) */
    get: operations['getJourneySummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/journeys/{id}/legs': {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    /**
     * Leg and stop deltas for Perlschnur timeline
     * @description Called once on CompanionScreen mount, then again when `alternativeAvailable` flag changes.
     */
    get: operations['getJourneyLegs']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/journeys/{id}/alternatives': {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    /** Current alternatives list (cached) */
    get: operations['listAlternatives']
    put?: never
    /**
     * Trigger fresh alternative recomputation
     * @description Triggers a new HAFAS call + BFS routing pass. Returns 202 immediately.
     *     Client polls GET /alternatives for results.
     */
    post: operations['triggerAlternativeComputation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trains/{number}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Validate train number and return metadata
     * @description Called from StartScreen before POST /journeys to avoid wasting a journey creation on an invalid train.
     *     `number` in path: whitespace-stripped, uppercased. Examples: ICE123, RB27, S3, IRE200.
     */
    get: operations['getTrain']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Station name autocomplete (proxied from HAFAS sidecar, Redis-cached 5min) */
    get: operations['searchStations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness probe */
    get: operations['healthCheck']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/readyz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness probe — checks Redis, Postgres, HAFAS connectivity */
    get: operations['readinessCheck']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CreateJourneyRequest: {
      /**
       * @description Train number. Normalized by backend: ICE123 and ICE 123 are identical.
       * @example ICE 123
       */
      trainNumber: string
      /**
       * @description HAFAS station ID. Never a name string. Use GET /stations to resolve names.
       * @example 8000105
       */
      destination: string
      /**
       * @description User assertion. Backend never rejects based on this; returns plausibility assessment.
       * @default true
       */
      iAmOnThisTrain: boolean
      filters?: components['schemas']['JourneyFilters']
    }
    JourneyFilters: {
      /**
       * @description Filter to DB-operated trains only. Default ON — user-toggleable.
       * @default true
       */
      dbOnly: boolean
      /**
       * @description Maximum transfers. null = no limit.
       * @default null
       */
      maxTransfers: number | null
      /**
       * @description Min transfer buffer thresholds:
       *     - aggressive: 3 minutes
       *     - normal: 8 minutes
       *     - cautious: 15 minutes
       * @default normal
       * @enum {string}
       */
      safetyLevel: 'aggressive' | 'normal' | 'cautious'
    }
    CreateJourneyResponse: {
      /** @example jrn_01j2k3m4n5p6q7r8 */
      journeyId: string
      plausibility: components['schemas']['Plausibility']
      summary: components['schemas']['JourneySummary']
      alternatives: components['schemas']['Alternative'][]
    }
    Plausibility: {
      /**
       * @description - high: train is running and destination is a valid future stop
       *     - low: train has passed destination or has no realtime data
       *     - unknown: train data unavailable from HAFAS
       * @enum {string}
       */
      onTrainConfidence: 'high' | 'low' | 'unknown'
      /** @description Human-readable reason when confidence is not high */
      reason?: string | null
    }
    JourneySummary: {
      /**
       * Format: date-time
       * @description Estimated arrival at destination. UTC ISO 8601.
       * @example 2026-06-10T17:24:00Z
       */
      eta: string
      /**
       * @description - ok: journey stable, all transfers safe
       *     - critical: at least one transfer tight or strong delay
       *     - failed: route no longer continuable (cancelled leg, missed connection, no onward service)
       * @enum {string}
       */
      status: 'ok' | 'critical' | 'failed'
      /** @description Minutes saved vs. original train ETA. Null when on original train. */
      timeGainVsOriginalMinutes?: number | null
      /** @description Minutes saved vs. previously active route. Null if no prior alternative selected. */
      timeGainVsCurrentRouteMinutes?: number | null
      /** @description Smallest transfer buffer across all transfers in current route. */
      minTransferBufferMinutes?: number | null
      /** @description True if at least one transfer is below the safety level threshold. */
      criticalTransfer: boolean
      /** @description True if a better (earlier ETA) alternative exists. */
      alternativeAvailable: boolean
      /**
       * @description HAFAS data quality for this journey.
       *     - high: full realtime data present for all active legs
       *     - low: realtime partially missing or older than 5 minutes
       *     - unavailable: no realtime data in HAFAS response
       *     Frontend shows a data-freshness indicator when not "high".
       * @enum {string}
       */
      dataConfidence?: 'high' | 'low' | 'unavailable'
      /** @description Null when journey is complete. */
      nextStep?: components['schemas']['NextStep'] | null
      /**
       * Format: date-time
       * @description When backend last successfully fetched HAFAS data. UTC ISO 8601.
       */
      dataFetchedAt: string
      /**
       * Format: date-time
       * @description When ETag last changed (state change). UTC ISO 8601.
       */
      lastUpdatedAt: string
    }
    NextStep: {
      /**
       * @description - ride: currently on a train, no action needed
       *     - transfer: upcoming transfer — details required
       *     - disembark: final destination, get off the train
       * @enum {string}
       */
      type: 'ride' | 'transfer' | 'disembark'
      /** @example Kassel Hbf */
      stationName: string
      /**
       * @description HAFAS station ID
       * @example 8000294
       */
      stationId: string
      /**
       * @description Train to board. Null for disembark.
       * @example RE 4321
       */
      trainNumber?: string | null
      /**
       * @description Departure platform when known.
       * @example 5
       */
      platform?: string | null
      /**
       * Format: date-time
       * @description Departure of connecting train. UTC ISO 8601. Null for ride/disembark.
       */
      departureTime?: string | null
      /** @description Minutes between arrival and departure at transfer point. */
      bufferMinutes?: number | null
    }
    Journey: {
      journeyId: string
      summary: components['schemas']['JourneySummary']
      legs: components['schemas']['Leg'][]
      stops: components['schemas']['Stop'][]
    }
    JourneyLegs: {
      legs: components['schemas']['Leg'][]
      stops: components['schemas']['Stop'][]
    }
    Leg: {
      legId: string
      /** @example ICE 123 */
      vehicleNumber: string
      /** @example ICE 123 */
      lineName: string
      /**
       * @description HAFAS operator string. Empirically verified against db.transport.rest.
       * @example DB Fernverkehr AG
       */
      operator: string
      /** Format: date-time */
      departureTimePlanned: string
      /** Format: date-time */
      departureTimeActual?: string | null
      /** Format: date-time */
      arrivalTimePlanned: string
      /** Format: date-time */
      arrivalTimeActual?: string | null
      delayMinutes?: number | null
      platformPlanned?: string | null
      platformActual?: string | null
      /** @enum {string} */
      status: 'planned' | 'running' | 'delayed' | 'cancelled'
      /** @default false */
      isWalkingSegment: boolean
    }
    Stop: {
      /** @example 8000294 */
      stationId: string
      /** @example Kassel Hbf */
      stationName: string
      /** Format: date-time */
      arrivalTimePlanned: string
      /** Format: date-time */
      arrivalTimeActual?: string | null
      /** Format: date-time */
      departureTimePlanned?: string | null
      /** Format: date-time */
      departureTimeActual?: string | null
      delayMinutes?: number | null
      platformPlanned?: string | null
      platformActual?: string | null
      /** @description Buffer at this stop if a transfer occurs here. */
      transferBufferMinutes?: number | null
    }
    Alternative: {
      journeyId: string
      summary: components['schemas']['JourneySummary']
      legs: components['schemas']['Leg'][]
    }
    AlternativesList: {
      data: components['schemas']['Alternative'][]
      /** @description Total alternatives found, may exceed returned list size. */
      totalCount?: number | null
    }
    Train: {
      /** @example ICE 123 */
      trainNumber: string
      /**
       * Format: date
       * @example 2026-06-10
       */
      date: string
      origin: components['schemas']['StationRef']
      destination: components['schemas']['StationRef']
      /** @description All stops including origin and destination. */
      stops?: components['schemas']['StationRef'][]
      /** @enum {string} */
      status: 'planned' | 'running' | 'delayed' | 'cancelled'
    }
    StationRef: {
      /**
       * @description HAFAS station ID
       * @example 8000105
       */
      id: string
      /** @example Frankfurt (Main) Hbf */
      name: string
    }
    StationList: {
      /** @description Empty array when no match. Never 404 for missing results. */
      stations: components['schemas']['StationRef'][]
    }
    ReadinessResponse: {
      /** @enum {string} */
      status: 'ok' | 'degraded' | 'unavailable'
      checks: {
        /** @enum {string} */
        redis: 'ok' | 'error'
        /** @enum {string} */
        postgres: 'ok' | 'error'
        /** @enum {string} */
        hafas: 'ok' | 'error'
      }
    }
    /** @description RFC 7807 Problem Details. type is a stable URN identifier, not a dereferenceable URL. */
    Problem: {
      /**
       * @description URN error identifier. Format: urn:verspbegl:error:<slug>
       * @example urn:verspbegl:error:train-not-found
       */
      type: string
      /** @example Train Not Found */
      title: string
      /** @example 404 */
      status: number
      /**
       * @description Human-readable, actionable error description.
       * @example Train ICE 123 does not operate on 2026-06-10.
       */
      detail?: string
      /**
       * @description Request path + X-Request-Id for log correlation.
       * @example /v1/trains/ICE123
       */
      instance?: string
      /** @description Field-level validation errors. Present on 422 responses only. */
      errors?: {
        /** @example destination */
        field: string
        /** @example Must be a valid HAFAS station ID. */
        message: string
      }[]
    }
  }
  responses: {
    /** @description Malformed request — unparseable JSON or missing Content-Type */
    MalformedRequest: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:malformed-request",
         *       "title": "Malformed Request",
         *       "status": 400,
         *       "detail": "Request body is not valid JSON.",
         *       "instance": "/v1/journeys"
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Semantic validation failure — valid JSON but invalid field values */
    ValidationError: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:validation-error",
         *       "title": "Validation Error",
         *       "status": 422,
         *       "detail": "Request body has invalid fields.",
         *       "instance": "/v1/journeys",
         *       "errors": [
         *         {
         *           "field": "destination",
         *           "message": "Must be a valid HAFAS station ID."
         *         },
         *         {
         *           "field": "filters.safetyLevel",
         *           "message": "Must be one of: aggressive, normal, cautious."
         *         }
         *       ]
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Train not found for this date */
    TrainNotFound: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:train-not-found",
         *       "title": "Train Not Found",
         *       "status": 404,
         *       "detail": "Train ICE 123 does not operate on 2026-06-10.",
         *       "instance": "/v1/trains/ICE123"
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Journey not found or expired */
    JourneyNotFound: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:journey-not-found",
         *       "title": "Journey Not Found",
         *       "status": 404,
         *       "detail": "Journey jrn_01j2k3m4n5 does not exist or has expired.",
         *       "instance": "/v1/journeys/jrn_01j2k3m4n5"
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Idempotency-Key reused with different request body */
    IdempotencyConflict: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:idempotency-conflict",
         *       "title": "Idempotency Conflict",
         *       "status": 409,
         *       "detail": "Idempotency-Key was already used with a different request body."
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Rate limit exceeded */
    TooManyRequests: {
      headers: {
        /** @description Seconds to wait. Client should apply exponential backoff: min(Retry-After × 2^n, 300). */
        'Retry-After'?: number
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:rate-limit-exceeded",
         *       "title": "Rate Limit Exceeded",
         *       "status": 429
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Backend dependency unavailable (HAFAS sidecar unreachable or MAX_ACTIVE_JOURNEYS capacity reached) */
    ServiceUnavailable: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:upstream-unavailable",
         *       "title": "Service Unavailable",
         *       "status": 503
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
    /** @description Unexpected server error */
    InternalError: {
      headers: {
        'X-Request-Id': components['headers']['RequestId']
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "urn:verspbegl:error:internal-error",
         *       "title": "Internal Server Error",
         *       "status": 500,
         *       "detail": "An unexpected error occurred."
         *     }
         */
        'application/problem+json': components['schemas']['Problem']
      }
    }
  }
  parameters: {
    /**
     * @description UUID v4 device identifier for abuse shaping.
     *     Generated on first app launch, stored in IndexedDB + localStorage backup.
     *     Falls back to IP-based rate limiting if absent.
     *     Not authentication — open API.
     */
    InstallId: string
    /**
     * @description Journey identifier. Format: jrn_<ulid-style>
     * @example jrn_01j2k3m4n5p6q7r8
     */
    JourneyId: string
  }
  requestBodies: never
  headers: {
    /**
     * @description Request limit per window
     * @example 60
     */
    RateLimitLimit: number
    /**
     * @description Requests remaining in current window
     * @example 47
     */
    RateLimitRemaining: number
    /**
     * @description Unix timestamp when window resets
     * @example 1749600420
     */
    RateLimitReset: number
    /** @description Server-generated request ID for log correlation. Echoed in error instance field. */
    RequestId: string
  }
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  createJourney: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
        /**
         * @description Optional idempotency key (10-minute window).
         *     Same key + identical canonical body → 200 with existing journey.
         *     Same key + different body → 409 Conflict.
         */
        'Idempotency-Key'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        /**
         * @example {
         *       "trainNumber": "ICE 123",
         *       "destination": "8000105",
         *       "iAmOnThisTrain": true,
         *       "filters": {
         *         "dbOnly": true,
         *         "maxTransfers": null,
         *         "safetyLevel": "normal"
         *       }
         *     }
         */
        'application/json': components['schemas']['CreateJourneyRequest']
      }
    }
    responses: {
      /** @description Existing journey returned (Idempotency-Key replay) */
      200: {
        headers: {
          'Idempotency-Replayed'?: boolean
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateJourneyResponse']
        }
      }
      /** @description Journey created */
      201: {
        headers: {
          /** @description /v1/journeys/{id} */
          Location?: string
          /** @description Present and true when returning existing journey via Idempotency-Key */
          'Idempotency-Replayed'?: boolean
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateJourneyResponse']
        }
      }
      400: components['responses']['MalformedRequest']
      409: components['responses']['IdempotencyConflict']
      422: components['responses']['ValidationError']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ServiceUnavailable']
    }
  }
  getJourney: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
      }
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Full journey */
      200: {
        headers: {
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Journey']
        }
      }
      404: components['responses']['JourneyNotFound']
      429: components['responses']['TooManyRequests']
      500: components['responses']['InternalError']
    }
  }
  deleteJourney: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
      }
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Journey terminated */
      204: {
        headers: {
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content?: never
      }
      404: components['responses']['JourneyNotFound']
      429: components['responses']['TooManyRequests']
    }
  }
  getJourneySummary: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
        /** @description ETag from previous response for conditional fetch */
        'If-None-Match'?: string
      }
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Journey summary (state changed since last ETag) */
      200: {
        headers: {
          /**
           * @description Format: <journeyId>:<redisLoadEpoch>:<counter>
           * @example jrn_01j2k3m4n5:1749600000:42
           */
          ETag?: string
          /** @example private, no-cache, must-revalidate */
          'Cache-Control'?: string
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JourneySummary']
        }
      }
      /** @description Not modified — ETag matches, no state change */
      304: {
        headers: {
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          [name: string]: unknown
        }
        content?: never
      }
      404: components['responses']['JourneyNotFound']
      429: components['responses']['TooManyRequests']
    }
  }
  getJourneyLegs: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
        'If-None-Match'?: string
      }
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Journey legs and stops */
      200: {
        headers: {
          ETag?: string
          /** @example private, no-cache, must-revalidate */
          'Cache-Control'?: string
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JourneyLegs']
        }
      }
      /** @description Not modified */
      304: {
        headers: {
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          [name: string]: unknown
        }
        content?: never
      }
      404: components['responses']['JourneyNotFound']
      429: components['responses']['TooManyRequests']
    }
  }
  listAlternatives: {
    parameters: {
      query?: {
        /** @description Maximum number of alternatives to return */
        limit?: number
      }
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
      }
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Alternatives list */
      200: {
        headers: {
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlternativesList']
        }
      }
      404: components['responses']['JourneyNotFound']
      429: components['responses']['TooManyRequests']
    }
  }
  triggerAlternativeComputation: {
    parameters: {
      query?: never
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
      }
      path: {
        /**
         * @description Journey identifier. Format: jrn_<ulid-style>
         * @example jrn_01j2k3m4n5p6q7r8
         */
        id: components['parameters']['JourneyId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Computation triggered */
      202: {
        headers: {
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'computing'
            /** @example /v1/journeys/jrn_01j2k3m4n5/alternatives */
            pollPath: string
          }
        }
      }
      404: components['responses']['JourneyNotFound']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ServiceUnavailable']
    }
  }
  getTrain: {
    parameters: {
      query?: {
        /** @description ISO 8601 date YYYY-MM-DD. Defaults to today in UTC. */
        date?: string
      }
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
      }
      path: {
        /** @description Train number — whitespace stripped, uppercased. ICE 123 → ICE123. */
        number: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Train found */
      200: {
        headers: {
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "trainNumber": "ICE 123",
           *       "date": "2026-06-10",
           *       "origin": {
           *         "id": "8000261",
           *         "name": "München Hbf"
           *       },
           *       "destination": {
           *         "id": "8011160",
           *         "name": "Berlin Hbf"
           *       },
           *       "stops": [],
           *       "status": "running"
           *     }
           */
          'application/json': components['schemas']['Train']
        }
      }
      400: components['responses']['MalformedRequest']
      404: components['responses']['TrainNotFound']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ServiceUnavailable']
    }
  }
  searchStations: {
    parameters: {
      query: {
        /** @description Search query, minimum 2 characters. Prefix + substring match, diacritic-insensitive. */
        q: string
        /** @description Maximum number of results */
        limit?: number
      }
      header?: {
        /**
         * @description UUID v4 device identifier for abuse shaping.
         *     Generated on first app launch, stored in IndexedDB + localStorage backup.
         *     Falls back to IP-based rate limiting if absent.
         *     Not authentication — open API.
         */
        'X-Install-Id'?: components['parameters']['InstallId']
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Station results. Empty array when no match — never 404. */
      200: {
        headers: {
          /** @example public, max-age=300 */
          'Cache-Control'?: string
          'X-RateLimit-Limit': components['headers']['RateLimitLimit']
          'X-RateLimit-Remaining': components['headers']['RateLimitRemaining']
          'X-RateLimit-Reset': components['headers']['RateLimitReset']
          'X-Request-Id': components['headers']['RequestId']
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "stations": [
           *         {
           *           "id": "8000105",
           *           "name": "Frankfurt (Main) Hbf"
           *         },
           *         {
           *           "id": "8000104",
           *           "name": "Frankfurt (Main) Süd"
           *         }
           *       ]
           *     }
           */
          'application/json': components['schemas']['StationList']
        }
      }
      400: components['responses']['MalformedRequest']
      429: components['responses']['TooManyRequests']
      503: components['responses']['ServiceUnavailable']
    }
  }
  healthCheck: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is alive */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "status": "ok"
           *     }
           */
          'application/json': {
            /** @enum {string} */
            status: 'ok'
          }
        }
      }
    }
  }
  readinessCheck: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service is ready */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
      /** @description Service not ready — one or more dependencies unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
    }
  }
}
